# Generated by Django 2.2.5 on 2020-11-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField()),
                ('Title', models.CharField(max_length=100)),
                ('Rating', models.FloatField()),
                ('Metascore', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Gross', models.IntegerField()),
                ('Votes_number', models.IntegerField()),
                ('Image', models.CharField(max_length=100)),
            ],
        ),
    ]
